server:
   port: 9898

logging:
   level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

spring:
    h2:
       console.enabled: true
    datasource:
       url: jdbc:h2:mem:/testdb/bocobidb
       username: bocobiuser
       password: bocobi
       driverClassName: org.h2.Driver
    jpa:
       hibernate:
             ddl-auto: create-drop
       properties:
          hibernate:
             show-sql: true
             generate-ddl: true
             use_sql_comments: true
             format_sql: true     